"""One-off batch: LLM-enrich the curated DEFAULT topics with comprehensive,
uncapped learning points + questions. Results are cached to JSON (resumable) and
emitted as app/content_generated.py, which the seeder merges additively on top of
the hand-authored content.py (dedup by title/prompt).

Run inside the backend container:
    docker compose exec -T backend python _enrich.py "Coding" "System Design" "AI Infra" "AI/ML"
Re-running skips topics already in the cache.
"""
import json
import os
import sys
import threading
from concurrent.futures import ThreadPoolExecutor, as_completed

from app import content, llm

CACHE = "/app/app/_generated_cache.json"
OUT = "/app/app/content_generated.py"
MAX_WORKERS = 4

_lock = threading.Lock()


def load_cache() -> dict:
    if os.path.exists(CACHE):
        with open(CACHE) as f:
            return json.load(f)
    return {}


def save_cache(cache: dict) -> None:
    with _lock:
        tmp = CACHE + ".tmp"
        with open(tmp, "w") as f:
            json.dump(cache, f, ensure_ascii=False, indent=1)
        os.replace(tmp, CACHE)


def enrich_one(domain: str, title: str) -> tuple[str, dict | None]:
    r = llm.generate_topic_content(title, domain)
    if not r:
        return title, None
    return title, {
        "points": [[lp.get("title", "").strip(), lp.get("details", "").strip()]
                   for lp in r.get("learning_points", []) if lp.get("title", "").strip()],
        "example": [q.strip() for q in r.get("example_questions", []) if q.strip()],
        "common": [q.strip() for q in r.get("common_questions", []) if q.strip()],
    }


def main(domains: list[str]) -> None:
    cache = load_cache()
    jobs = []
    for domain in domains:
        for spec in content.CONTENT_BY_DOMAIN.get(domain, []):
            title = spec["title"]
            if title not in cache:
                jobs.append((domain, title))
    print(f"{len(jobs)} topics to enrich ({len(cache)} already cached). Workers={MAX_WORKERS}", flush=True)

    done = 0
    with ThreadPoolExecutor(max_workers=MAX_WORKERS) as ex:
        futs = {ex.submit(enrich_one, d, t): t for d, t in jobs}
        for fut in as_completed(futs):
            title = futs[fut]
            try:
                title, data = fut.result()
            except Exception as e:  # noqa: BLE001
                print(f"  FAIL {title[:50]}: {e}", flush=True)
                continue
            done += 1
            if data is None:
                print(f"  [{done}/{len(jobs)}] NONE {title[:50]}", flush=True)
                continue
            cache[title] = data
            save_cache(cache)
            print(f"  [{done}/{len(jobs)}] {len(data['points'])} pts, "
                  f"{len(data['example'])+len(data['common'])} qs  {title[:50]}", flush=True)

    emit(cache)
    print(f"Wrote {OUT} with {len(cache)} topics.", flush=True)


def emit(cache: dict) -> None:
    lines = [
        '"""AUTO-GENERATED by _enrich.py — comprehensive LLM-authored learning points',
        "+ questions, merged additively by the seeder on top of the curated content.py.",
        'Regenerate with _enrich.py; do not hand-edit."""',
        "",
        "GENERATED: dict[str, dict] = {",
    ]
    for title in sorted(cache):
        d = cache[title]
        lines.append(f"    {title!r}: {{")
        lines.append('        "points": [')
        for t, n in d["points"]:
            lines.append(f"            ({t!r}, {n!r}),")
        lines.append("        ],")
        lines.append(f'        "example": {d["example"]!r},')
        lines.append(f'        "common": {d["common"]!r},')
        lines.append("    },")
    lines.append("}")
    with open(OUT, "w") as f:
        f.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    domains = sys.argv[1:] or ["Coding", "System Design", "AI Infra", "AI/ML"]
    main(domains)
