"""One-off batch: reorder each topic's learning points so related points are
GROUPED together and in a sensible learning sequence (e.g. all DFS points in one
run, then all BFS points — not interleaved).

For every default topic in the target domains it reads the topic's current
default learning points (owner_id IS NULL) straight from the DB, asks the LLM to
regroup + resequence them (returning a permutation of the exact titles), and
emits app/content_point_order.py as POINT_ORDER (topic title -> ordered point
titles). The seeder then re-applies Subtopic.order from that map on every
startup — idempotent, default points only, user-owned points untouched.

Run inside the backend container (from /app, where the `app` package lives):
    docker compose exec -T backend python scripts/_order_points.py "Coding" "System Design" "AI Infra" "AI/ML"
Resumable: a topic is skipped if it's cached AND its current point set is
unchanged. The returned order is always reconciled to a full permutation (any
title the model drops is appended in its original order; unknown titles ignored).
"""
import json
import os
import sys
import threading
import time
from concurrent.futures import ThreadPoolExecutor, as_completed

# This one-off lives in backend/scripts/ but imports the `app` package at the
# backend root — put that root on sys.path however the script is launched.
_HERE = os.path.dirname(os.path.abspath(__file__))
_ROOT = os.path.dirname(_HERE)
sys.path.insert(0, _ROOT)

from sqlalchemy import select  # noqa: E402

from app import llm  # noqa: E402
from app.database import SessionLocal  # noqa: E402
from app.models import Domain, Subtopic, Topic  # noqa: E402

CACHE = os.path.join(_HERE, "_point_order_cache.json")
OUT = os.path.join(_ROOT, "app", "content_point_order.py")
MAX_WORKERS = 4
DEFAULT_DOMAINS = ["Coding", "System Design", "AI Infra", "AI/ML"]

_lock = threading.Lock()


def load_cache() -> dict:
    if os.path.exists(CACHE):
        with open(CACHE) as f:
            return json.load(f)
    return {}


def save_cache(cache: dict) -> None:
    with _lock:
        tmp = CACHE + ".tmp"
        with open(tmp, "w") as f:
            json.dump(cache, f, ensure_ascii=False, indent=1)
        os.replace(tmp, CACHE)


def read_topics(domains: list[str]) -> dict[str, dict]:
    """topic title -> {domain, points: [titles in current order]} for default
    topics + default points in the given domains."""
    db = SessionLocal()
    try:
        rows = db.execute(
            select(Domain.name, Topic.title, Subtopic.title)
            .join(Topic, Topic.domain_id == Domain.id)
            .join(Subtopic, Subtopic.topic_id == Topic.id)
            .where(
                Domain.name.in_(domains),
                Topic.owner_id.is_(None),
                Subtopic.owner_id.is_(None),
            )
            .order_by(Topic.title, Subtopic.order, Subtopic.id)
        ).all()
    finally:
        db.close()
    out: dict[str, dict] = {}
    for domain, topic_title, point_title in rows:
        rec = out.setdefault(topic_title, {"domain": domain, "points": []})
        rec["points"].append(point_title)
    return out


def reconcile(original: list[str], returned: list[str] | None) -> tuple[list[str], bool]:
    """Force the model's answer into a full permutation of `original`. Returns
    (ordered, exact) where exact=True iff the model already returned every title
    once with no extras."""
    oset = set(original)
    seen: set[str] = set()
    out: list[str] = []
    for t in returned or []:
        if t in oset and t not in seen:
            out.append(t)
            seen.add(t)
    for t in original:  # append any titles the model dropped, original order
        if t not in seen:
            out.append(t)
            seen.add(t)
    exact = bool(returned) and len(returned) == len(original) and set(returned) == oset
    return out, exact


# Each failed `claude -p` call already burns ~3 min (the CLI retries internally
# before surfacing a 529), so keep external retries low and lean on the script's
# resumability — just re-run it after a broad overload clears.
RETRIES = 2


def order_one(topic_title: str, domain: str, points: list[str]) -> tuple[str, list[str] | None, bool]:
    # Retry with backoff: order_topic_points returns None on any failure
    # (including transient server overload), which we don't want to cache.
    for attempt in range(RETRIES):
        returned = llm.order_topic_points(topic_title, domain, points)
        if returned is not None:
            ordered, exact = reconcile(points, returned)
            return topic_title, ordered, exact
        if attempt < RETRIES - 1:
            time.sleep(3 * (attempt + 1))
    return topic_title, None, False


def emit(cache: dict) -> None:
    lines = [
        '"""AUTO-GENERATED by scripts/_order_points.py — do not hand-edit.',
        "",
        "Canonical within-topic learning-point ordering: topic title -> point titles",
        "in grouped, pedagogical order. seed.py re-applies Subtopic.order from this to",
        'default points on every startup. Regenerate with _order_points.py."""',
        "",
        "POINT_ORDER: dict[str, list[str]] = {",
    ]
    for title in sorted(cache):
        ordered = cache[title]["ordered"]
        lines.append(f"    {title!r}: [")
        for pt in ordered:
            lines.append(f"        {pt!r},")
        lines.append("    ],")
    lines.append("}")
    with open(OUT, "w") as f:
        f.write("\n".join(lines) + "\n")


def main(domains: list[str]) -> None:
    if not llm.ai_configured():
        print("LLM not configured (need CLAUDE_CODE_OAUTH_TOKEN or ANTHROPIC_API_KEY). Aborting.", flush=True)
        sys.exit(1)
    topics = read_topics(domains)
    cache = load_cache()

    jobs = []
    for topic_title, rec in topics.items():
        pts = rec["points"]
        if len(pts) < 2:
            continue  # nothing to order
        cached = cache.get(topic_title)
        if cached and set(cached.get("source", [])) == set(pts):
            continue  # already ordered this exact point set
        jobs.append((topic_title, rec["domain"], pts))
    print(f"{len(topics)} topics scanned, {len(jobs)} to (re)order. Workers={MAX_WORKERS}", flush=True)

    done = 0
    with ThreadPoolExecutor(max_workers=MAX_WORKERS) as ex:
        futs = {ex.submit(order_one, t, d, p): (t, p) for t, d, p in jobs}
        for fut in as_completed(futs):
            topic_title, pts = futs[fut]
            try:
                topic_title, ordered, exact = fut.result()
            except Exception as e:  # noqa: BLE001
                print(f"  FAIL {topic_title[:50]}: {e}", flush=True)
                continue
            done += 1
            if ordered is None:
                print(f"  [{done}/{len(jobs)}] NONE {topic_title[:50]}", flush=True)
                continue
            cache[topic_title] = {"source": pts, "ordered": ordered}
            save_cache(cache)
            flag = "" if exact else " (reconciled)"
            print(f"  [{done}/{len(jobs)}] {len(ordered)} pts{flag}  {topic_title[:50]}", flush=True)

    emit(cache)
    print(f"Wrote {OUT} with ordering for {len(cache)} topics.", flush=True)


if __name__ == "__main__":
    main(sys.argv[1:] or DEFAULT_DOMAINS)
